# Generated by Django 3.2.5 on 2021-12-03 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_Start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 3, 13, 3, 13, 613436), null=True),
        ),
    ]
